version: '3.8'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  connect:
    build:
      context: ./connect
      dockerfile: Dockerfile
    container_name: connect
    hostname: connect
    ports:
      - "8083:8083"
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my-connect-configs
      - OFFSET_STORAGE_TOPIC=my-connect-offsets
      - BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - zookeeper
      - kafka

  postgres:
    image: debezium/postgres:15
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    ports:
      - 19120:19120

  minio:
    image: quay.io/minio/minio:RELEASE.2022-05-26T05-48-41Z
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
    volumes:
      - ./volume/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 5

  createbuckets:
    image: minio/mc
    container_name: createbuckets
    links:
      - minio:minio
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      /usr/bin/mc config host add myminio http://minio:9000 minio minio123 &&
      /usr/bin/mc rm -r --force myminio/commerce || true &&
      /usr/bin/mc mb myminio/commerce &&
      /usr/bin/mc policy download myminio/commerce;
      "

  pyspark:
    build:
      context: ./pyspark
      dockerfile: Dockerfile
    container_name: pyspark
    environment:
      - SPARK_DRIVER_MEMORY=12g
      - SPARK_EXECUTOR_MEMORY=12g
      - SPARK_EXECUTOR_CORES=*
    volumes:
      - ./pyspark/scripts:/opt/code/
      - ./data:/opt/data
    depends_on:
      - zookeeper
      - kafka
      - minio

  datagen:
    build:
      context: .
      dockerfile: ./datagen/Dockerfile
    container_name: datagen
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    restart: on-failure
    depends_on:
      - postgres
    entrypoint:
      - python
      - ./data_gen.py

  dremio:
    build: 
      context: ./dremio
      dockerfile: Dockerfile
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    container_name: dremio
    volumes:
      - ./volume/dremio:/var/lib/dremio

  superset:
    build:
      context: .
      dockerfile: ./superset/Dockerfile
    container_name: superset
    ports:
      - 8088:8088
    volumes:
      - ./volume/superset:/var/lib/superset
